name:                hs-web
version:             0.1.0.0
github:              "nieled/hs-web"
license:             BSD3
author:              "Daniel Calle"
maintainer:          "nieled@riseup.net"
copyright:           "2021 Daniel Calle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nieled/hs-web#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- time
- time-lens
- regex-tdfa
- raw-strings-qq
- aeson
- template-haskell
- mtl
- data-has
- string-random
- katip
- resource-pool
- postgresql-simple
- postgresql-simple-migration

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell
- ConstraintKinds
- FlexibleContexts
- GeneralizedNewtypeDeriving

library:
  source-dirs: src

executables:
  hs-web-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-web

tests:
  hs-web-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-web
