name: Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHC
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: "8.10.4"
          enable-stack: true

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build and run tests
          run: "stack test --fast --no-terminal --system-ghc"
